### ISSUE TITLE
Lenovo T480 / T480s / X1C6 throttling issues

### ISSUE THREAD

**Issue by ColinIanKing** [intel/thermal_daemon#268] opened 2020-09-01 13:07 UTC
Hi there,

We're seeing some users with Lenovo laptops with Thermald are experiencing some issues ( https://www.reddit.com/r/thinkpad/comments/870u0a/t480s_linux_throttling_bug/ ) and a user has a workaround with their own daemon:

"As discovered by DEvil0000 the Linux Thermal Monitor (thermald) can conflict with the purpose of this tool. In particular, thermald might be pre-installed (e.g. on Ubuntu) and configured in such a way to keep the CPU temperature below a certain threshold (~80 'C) by applying throtthling or messing up with RAPL or other CPU-specific registers. I strongly suggest to either disable/uninstall it or to review its default configuration." , 

see:  https://github.com/erpalma/throttled

Is this a known thermald issue and is there a way to address this kind of behaviour?

**Comment by spandruvada** [comment] 2020-09-01 15:33
Hi,

This is not a thermald issue. This device powers up with low TDP and TCC offset. Two years back kernel didn’t have rapl-mmio driver and way to adjust TCC offset. But we have this support from a year.
The previous thermald 1.9 version had a workaround for this problem. So I think it fixed for many users.

But with the new Matthew’s patches instead of workaround the adaptive policy set the power and tcc limit. I think this system was his motivation.

But there is a report that even with this one system doesn’t work because there is no action to set power and tcc limit. So that is still unknown. Only Lenovo can tell what’s happening.

But Lenovo has firmware solution, so they want thermald to exit. So this issue may  be solved by BIOS upgrade.

Thanks!

**Comment by fthx** [comment] 2020-09-03 16:48
Hi,

There's a long thread here : 
https://forums.lenovo.com/t5/Other-Linux-Discussions/X1C6-T480s-low-cTDP-and-trip-temperature-in-Linux/m-p/4028489?page=44

Well, I own a T480s running Ubuntu 20.04 (and before that, previous Ubuntus...). That's a long standing bug.

AFAIK : 
- Lenovo won't push any related firmware update for older models (<= 480), if Mark from Lenovo is right in the thread above ; 
- Latest 2.3 thermald from Groovy does not improve the throttling comparing to 1.9 version, if Focal's kernel 5.4 is used ; 
- Replacing the thermald's auto config file created by dptfxtract with a void one (just headers + model name, not the thermal stuff) does partially solve the problem (running 8 threads after roughly 30 s : 2400 MHz -> 2700 MHz to 2900 MHz with a i7 8550u) ;
- Using the Groovy's 5.8 kernel and Groovy's 2.3 thermald without using any thermald's config hack does hugely improve things, as the frequency (very) slowly decreases to reach ~2700 MHz and the power usage is quite high ~25 W for CPU.

I noticed that, in the latest setup above, thermald does use much more cpu (in powertop) than running through the 5.4 kernel. I don't know if it's related to this bug report, tough...

**Comment by fthx** [comment] 2020-10-21 19:29
@ColinIanKing 
I've now installed the official pre-hwe 5.8 kernel which is present now in the Focal repository, and thermald 2.3-4 from Sid/Groovy.
CPU temps reach 97°C and my T480s (Intel GPU) seems to run at full available power.
@spandruvada suggested me to upgrade to thermald 2.3 after I did this Groovy 5.8 then 5.8 Focal hwe upgrade, to get the adaptive feature.

I don't know all the SRU limitations but clearly when the 5.8 hwe kernel stack will be officially available in Focal, it would be a pity to not get 2.3+ thermald. Maybe a thermald-hwe ?

**Comment by fthx** [comment] 2021-02-25 09:19
Trying the Ubuntu OEM 5.10 kernel, I see that thermald does not behave like running the 5.8 official Ubuntu 20.04 kernel.
AC plugged, s-tui stress test leads to ~ 2400 MHz per cpu instead of ~ 3000 MHz running 5.8.
Is that attended and is there a solution?

**Comment by benzea** [comment] 2021-02-25 12:01
That is intended. thermald will disable itself on these machines, as the firmware based solution is better in general.

Unfortunately, the check might false-positive on some machines though. If your machine is supported, try using Fn+HML (H: performance, M: balanced, L: quiet) to switch the performance mode.

**Comment by fthx** [comment] 2021-02-25 13:21
Ok, thanks.
Unfortunately, my Thinkpad T480s does not react to Fn+HML. Is there a way to force thermald to be activated?

**Comment by benzea** [comment] 2021-02-25 14:23
Yes, you can pass `--ignore-cpuid-check`

**Comment by fthx** [comment] 2021-02-25 14:34
Ok great, I will try this.
The problem is mainly that my laptop keeps cold even on a firm desktop, running old Focal thermald. :-)

Anyway, very happy with default 5.8 Ubuntu kernel and thermald 2.4.2 (from Debian Sid because some dependencies issues with Hirsute one). Nothing to do, just install this thermald and my laptop runs as it should do, reading the specs. Wouldn't it be a good thing that Focal upgrades its thermald version to achieve some useful recent thermald features for kernel 5.8+ ?

**Comment by fthx** [comment] 2021-02-25 16:00
Well, it did not work:
`[/sys/devices/platform/thinkpad_acpi/dytc_lapmode] present: Thermald can't run on this platform`

Just to be sure, the option had to be added in thermald systemd's service file?

**Comment by benzea** [comment] 2021-02-25 17:05
I think the warning is always printed. I guess you might also need to remove the `--adaptive` option.

**Comment by fthx** [comment] 2021-02-25 17:11
Argh, I did not remove adaptive argument. I'll try that.

**Comment by fthx** [comment] 2021-02-27 07:55
Well, it did not work either.
thermald daemon is loaded but still does not prevent throttling ~ 2400 MHz instead of ~ 3000 MHz with 5.8.

**Comment by fthx** [comment] 2021-03-01 20:00
Some related infos here:
https://forums.lenovo.com/t5/Other-Linux-Discussions/X1C6-T480s-low-cTDP-and-trip-temperature-in-Linux/m-p/4028489?page=46#5193873
Well, I should have had a look as I know this thread!

So with --ignore* and --workaround-enabled, it works, but is less efficient than --adaptive in 5.8 kernel.

**Comment by spandruvada** [comment] 2021-03-01 20:38
On Mon, 2021-03-01 at 12:00 -0800, fthx wrote:
> Some related infos here:
> https://forums.lenovo.com/t5/Other-Linux-Discussions/X1C6-T480s-low-cTDP-and-trip-temperature-in-Linux/m-p/4028489?page=46#5193873
> Well, I should have had a look as I know this thread!
> 
> So with --ignore* and --workaround-enabled, it works, but is less
> efficient than --adaptive in 5.8 kernel.
> 
May be a thermald change to include ignore_cpuid_check check.
Is this you want to test?

**Comment by spandruvada** [comment] 2021-03-01 20:50
Something like this as impacts several models.
[t480-workaround.zip](https://github.com/intel/thermal_daemon/files/6064380/t480-workaround.zip)

**Comment by fthx** [comment] 2021-03-01 21:00
If I do understand your patch, it would allow running thermald in adaptive mode when ignore-cpuid-check is present?

**Comment by spandruvada** [comment] 2021-03-01 21:03
On Mon, 2021-03-01 at 13:01 -0800, fthx wrote:
> If I do understand your patch, it would allow running thermald in
> adaptive mode when ignore-cpuid-check is present?
Yes.

**Comment by fthx** [comment] 2021-03-01 21:07
Oh so it would be great, as thermald's adaptive mode in 5.8 hwe Ubuntu kernel works (without any tweak) very well for my T480s, as my cpu reaches (AC mode in TLP) 97 °C despite Lenovo firmware flaws.

**Comment by spandruvada** [comment] 2021-03-01 22:59
On Mon, 2021-03-01 at 13:07 -0800, fthx wrote:
> Oh so it would be great, as thermald's adaptive mode in 5.8 hwe
> Ubuntu kernel works (without any tweak) very well for my T480s, as my
> cpu reaches (AC mode in TLP) 97 °C despite Lenovo firmware flaws.
> 
Test the patch and let me know how it goes. You can simply use "git
apply " and apply this patch on thermald source checkout and build.

**Comment by fthx** [comment] 2021-03-02 08:11
Ok. Please excuse my hand-made operations, I'm far from an git/build expert. So tell me if I'm wrong:
1) I downloaded your source zip, extracted it
2) I patched the adaptive file (I verified it after that to be sure)
3) I built thermald on Ubuntu 20.04 up to date
4) I copied the thermald bin file to /usr/sbin (**simply replacing the old one (am I right here?)**, which was much smaller 600 Ko vs 15 Mb, is that normal?)
5) I set the thermald systemd's service file  with adaptive and ignore-cpuid-check options, not workaround-enabled
6) I rebooted my T480s

Results:
1) thermald is loaded
2) I get no error messages in logs ("thermald" search)
3) I did a stress test using s-tui (8 threads, 1m30s ~)
4) My cpu reached 97 °C (as intended) and ~ 3000 MHz (as intended), so it's quite the same behaviour than running 5.8 hwe kernel
5) My exact kernel version: 5.10.0-1015-oem from Ubuntu official repository @ColinIanKing 

Well, it seems to be successful. Thanks!

**Comment by spandruvada** [comment] 2021-03-02 15:55
@benzea 
Do we want to do this change? Looks like you are involved in the thread with Lenovo.

**Comment by ubivent-seuffert** [comment] 2021-03-02 16:11
with this patch by @spandruvada on my T580 , i am seeing a nice freq scaling behavior of >3,4ghz/45W/90°C

**Comment by benzea** [comment] 2021-03-02 16:13
@spandruvada that makes sense to me. After all, the option should do what it advertises.

I am a bit surprised it actually works tbh. I thought in most cases the adaptive code picks some not-very-useful profile all the time. But, good for you :-)

**Comment by spandruvada** [comment] 2021-03-02 16:22
On Tue, 2021-03-02 at 08:14 -0800, Benjamin Berg wrote:
> @spandruvada that makes sense to me. After all, the option should do
> what it advertises.
> 
> I am a bit surprised it actually works tbh. I thought in most cases
> the adaptive code picks some not-very-useful profile all the time.
> But, good for you :-)
This is a simple change. This can be easily back ported.

Thanks.

**Comment by fthx** [comment] 2021-03-02 16:48
@benzea
In my case, adaptive option allows me to reach full fan speed (~ 5090 rpm for T480s, 3000 MHz 8 threads used).
Not workaround-enabled option, which is better than nothing but as far I remember reaches ~ 4600 rpm and 2800 MHz.
And workaround-enabled does not have a sleek behavior, it starts when cpu freq is beginning lowering (as far as I saw that during s-tui stress test).
So I damn don't know how adaptive works, but it does for T480s!! :-)

**Comment by spandruvada** [comment] 2021-03-02 22:22
I pushed this fix. But will not suggest distro to use --ignore-cpu-id by default.

**Comment by ColinIanKing** [comment] 2021-03-03 10:56
Thanks for the fix. I've uploaded the latest release to Debian, it will get sync'd into Ubuntu Hirsute within a few days.

**Comment by nariox** [comment] 2021-03-03 18:54
I have modified the source file for Archlinux. It uses the same version as the current one, so the patch will be overridden when a new version comes out (hopefully by 2.4.3, which also contains the patch)
[LINK](https://www.dropbox.com/s/cbgvmko4f2ms1n5/thermald-2.4.2-1.src.tar.zst?dl=0)

**Comment by xvitaly** [comment] 2021-03-03 20:09
Please fix checks on T480(s). These laptops has no firmware support, but thermald is now working on them without the `--ignore-cpu-id` flag.

**Comment by spandruvada** [comment] 2021-03-03 20:59
Even if they don't have firmware support, they are indicating support by the kernel driver. So that issue needs to be fixed in the Lenovo kernel driver.

**Comment by fthx** [comment] 2021-03-03 21:19
@mrhpearson

I installed the new thermald 2.4.3 from Debian Sid. I did a stress test. All is ok from my side.

**Comment by mrhpearson** [comment] 2021-03-04 03:15
> Even if they don't have firmware support, they are indicating support by the kernel driver. So that issue needs to be fixed in the Lenovo kernel driver.

Agreed - this one is on my todo list.

Thanks for your work on this on the thermald side - looks good

**Comment by fthx** [comment] 2021-06-05 07:41
I've just installed Debian 11 and noticed it contains thermald 2.4.2... Let's go for Sid's package.

Well, more important, there is a typo:

```
Release 2.4.3
- Allow --ingore-cpuid-check to use with --adaptive option
```

@spandruvada

**Comment by spandruvada** [comment] 2022-01-12 16:15
I will close this issue. I don't think anything to do in the thermald.

**Closed by spandruvada** 2022-01-12 16:15 UTC
