### ISSUE TITLE
cpuFan and gfxFan

### ISSUE THREAD

**Issue by daringer** [intel/thermal_daemon#62] opened 2015-06-12 22:32 UTC
from my (subjective) view the (my) fans are not set by thermald.... My config is here: http://pastebin.com/NQ4vYrJF - anyways I bet I just can't configure this thing ;) Why I am writing is a direct consequence from this issue: It is pretty rough (for me) to extract useful information from the logging, neither "debug" nor "test-mode" or the regular logging helped me to debug my problem.

I've manually set both fans (using this kernel-module to control them [asus-fan](https://github.com/daringer/asus-fan) thus could be my lousy bug ) to a fixed value to hear the thermald changes, nothing happens, thus I thought (as both don't appear inside the log) the config file is not read. Inserting a parsing error, leads to a warning inside the log ;) to make it short, I would like to motivate the reorganization of the log-output:
- startup: clearly mention each entity, without details, as user I would like to know who is how participating to the game (cooling devices, zones, sensors) and maybe their initial value and interval.
-  I get a lot of `thd_trip_cdev_state_reset` (11 in one second for me), (could also be a performance issue if it further scales) ... 
- In general my proposal would be, less technical more informal. E.g., I have not yet clearly managed to find out why my fans are not regulated. I don't whether this is me (hardware, kernel-module) or thermald (not seeing them, don't caring) . Thus a simple message like "Temp over X increasing cooling intensity using ZXY" could really help...
- avoid redundancy (why is there i.e., 20mins after startup still a `/sys/class/..../` path being shown)
-  and finally: a figure of merit : every now and then an overall view: "the computer is currently very hot (75°) and the cooling devices can't increase intensity" could also be formal like a "happines" ;D or "coolness" ...something I could log/show and easily adapt/understand....

Btw. I really like the dbus interface, very nice! Playing aruond with the shell-script, some feedback for this:
- option 0-4 show alot of log-output, but seem not to change anything substantial.
- setting min-temp with 5-6 also seems to have no immediate effect
- 7-8 show up inside the log -> working (despite the fact, that terminate/disable mens spamming the log with nearly 6000(!) log-msgs within one second ;D)
- the counts, means "H", "I" and "M" seem correct an reasonable
- the sefl-tests seem to do nothing ("G", "F")
- Trip information "L" leads to an assertion: `marshal_collection_array: "assertion 'array != NULL' failedunable to append OUT arg of type GArray_gint_ for GetZoneTripAtIndex: NULLupdate_pid 1434147793 1434147785 60995 31195.3 -31190`
- "N" "J", "K" all deliver some information, but always only for the first item...

I added cmd-line argument pass-trough to the script, so now one gets the easy chance to browse through all sensors and stuff. Pull request pending if you wanna have it, surely add some more based on your interface ....

thanks for the great work, cheers

**Comment by spandruvada** [comment] 2015-06-15 18:33
On Fri, 2015-06-12 at 15:32 -0700, Markus Meissner wrote:
> from my (subjective) view the (my) fans are not set by thermald.... My
> config is here: http://pastebin.com/NQ4vYrJF - anyways I bet I just
> can't configure this thing ;) Why I am writing is a direct consequence
> from this issue: It is pretty rough (for me) to extract useful
> information from the logging, neither "debug" nor "test-mode" or the
> regular logging helped me to debug my problem.
> 
> I've manually set both fans (using this kernel-module to control them
> asus-fan thus could be my lousy bug ) to a fixed value to hear the
> thermald changes, nothing happens, thus I thought (as both don't
> appear inside the log) the config file is not read. Inserting a
> parsing error, leads to a warning inside the log ;) to make it short,
> I would like to motivate the reorganization of the log-output:
> 
>       * startup: clearly mention each entity, without details, as user
>         I would like to know who is how participating to the game
>         (cooling devices, zones, sensors) and maybe their initial
>         value and interval.
>       * I get a lot of thd_trip_cdev_state_reset (11 in one second for
>         me), (could also be a performance issue if it further
>         scales) ... 
>       * In general my proposal would be, less technical more informal.
>         E.g., I have not yet clearly managed to find out why my fans
>         are not regulated. I don't whether this is me (hardware,
>         kernel-module) or thermald (not seeing them, don't caring) .
>         Thus a simple message like "Temp over X increasing cooling
>         intensity using ZXY" could really help...
>       * avoid redundancy (why is there i.e., 20mins after startup
>         still a /sys/class/..../ path being shown)
>       * and finally: a figure of merit : every now and then an overall
>         view: "the computer is currently very hot (75°) and the
>         cooling devices can't increase intensity" could also be formal
>         like a "happines" ;D or "coolness" ...something I could
>         log/show and easily adapt/understand....

I see your config. The two cooling devices CPUFan and GFXFan, I don't
see their definition (what sysfs, min/max). If they are exposed via
Linux thermal interface, then thermald can find them. If they are using
some special sysfs, then you have to define them.
You can see  Lenovo Thinkpad X220 fan example used by some user.
man thermal-conf.xml
and look at Example 3.

> 
> Btw. I really like the dbus interface, very nice! Playing aruond with
> the shell-script, some feedback for this:
This shell script is just for test. The idea is dbus messages can be
used to control.
> 
>       * option 0-4 show alot of log-output, but seem not to change
>         anything substantial.
>       * setting min-temp with 5-6 also seems to have no immediate
>         effect
>       * 7-8 show up inside the log -> working (despite the fact, that
>         terminate/disable mens spamming the log with nearly 6000(!)
>         log-msgs within one second ;D)
>       * the counts, means "H", "I" and "M" seem correct an reasonable
>       * the sefl-tests seem to do nothing ("G", "F")
>       * Trip information "L" leads to an assertion:
>         marshal_collection_array: "assertion 'array != NULL'
>         failedunable to append OUT arg of type GArray_gint_ for
>         GetZoneTripAtIndex: NULLupdate_pid 1434147793 1434147785 60995
>         31195.3 -31190

I will try to reproduce. This should be fixed.

>       * "N" "J", "K" all deliver some information, but always only for
>         the first item...
As said the test is passing parameter as 0, so this the first one.
You should check src/thd_dbus_interface.xml for the dbus interface
details.

> 
> I added cmd-line argument pass-trough to the script, so now one gets
> the easy chance to browse through all sensors and stuff. Pull request
> pending if you wanna have it, surely add some more based on your
> interface ....
I will take a look.

Thanks,
Srinivas

**Comment by daringer** [comment] 2015-06-21 11:23
thx for not throwing "RTFMs" on me, in fact I totally missed the config file related manpage...
Both fans are exposed through the hwmon interface, thus I took as you proposed, example 3 as a template and now I have this: https://github.com/daringer/asus-fan/blob/master/misc/thermald/thermal-conf.xml

Currently this works pretty good (after setting up a dir, where  symlinks to the hwmon interfaces are provided: https://github.com/daringer/asus-fan/blob/master/misc/create_symlinks.sh), the fans are both controlled - looks good - nevertheless the log shows me this: `XML zone: invalid sensor type die_sens`, which I don't understand as there is a definition for exactly this type, but obviously I am missing something....

Still, there are some open questions:
- Is it possible to disable the auto-recognition of cooling-devs, sensors? - In order to have a thermald running exactly my config---instead of the automatically generated with my config being "on-top-of"-the original configuration.

- Is it possible to cleanup the configuration from anything that is (auto-)'preconfigured' (yes, auto-config is great, but the classic configuration should (imho) not be underestimated especially on exotic hardware and/or software)

- First I was not giving a `<type>passive</type>` in TripPoints, leading to   `User defined max temperature 5`, which activated all possible cooling devices instantly. Is this behavior wanted? Especially, "user-temp" seems to be implicitly set by TripPoint->Type="passive"->Temp, which seems neither documented (I could have missed that) nor intuitive (for me).

- My current [config](https://github.com/daringer/asus-fan/blob/master/misc/thermald/thermal-conf.xml) defines "parallel" for both fans, further all other attributes are identical, nevertheless the values set (0...255) differ on both fans. E.g., CPUFan: 255 GFXFan: 215 ... Seems like I do not understand this option, could you maybe explain why this happens?

**Comment by spandruvada** [comment] 2015-06-22 00:46
On Sun, 2015-06-21 at 04:23 -0700, Markus Meissner wrote:
> thx for not throwing "RTFMs" on me, in fact I totally missed the
> config file related manpage...
> Both fans are exposed through the hwmon interface, thus I took as you
> proposed, example 3 as a template and now I have this:
> https://github.com/daringer/asus-fan/blob/master/misc/thermald/thermal-conf.xml
> 
> Currently this works pretty good (after setting up a dir, where
> symlinks to the hwmon interfaces are provided:
> https://github.com/daringer/asus-fan/blob/master/misc/create_symlinks.sh), the fans are both controlled - looks good - nevertheless the log shows me this: XML zone: invalid sensor type die_sens, which I don't understand as there is a definition for exactly this type, but obviously I am missing something....

As you have noticed, thermald loads all sensors and cooling devices from
thermal sysfs (/sys/class/thermal). If it finds another sensor in config
for a zone, then it needs a definition for that sensor in the sensor
block of config, where it has definition for name and path.
> 
> Still, there are some open questions:
> 
>       * Is it possible to disable the auto-recognition of
>         cooling-devs, sensors? - In order to have a thermald running
>         exactly my config---instead of the automatically generated
>         with my config being "on-top-of"-the original configuration.
We had this but not many folks were able to configure so even default
controls were disabled, for which there is no configuration is required.
But we can add this back with a command line option.

>       * Is it possible to cleanup the configuration from anything that
>         is (auto-)'preconfigured' (yes, auto-config is great, but the
>         classic configuration should (imho) not be underestimated
>         especially on exotic hardware and/or software)
Didn't get this question. We only generate the auto configuration file
for devices in which ACPI thermal relationship table exists.
>         
>       * First I was not giving a <type>passive</type> in TripPoints,
>         leading to User defined max temperature 5, which activated all
>         possible cooling devices instantly. Is this behavior wanted?
>         Especially, "user-temp" seems to be implicitly set by
>         TripPoint->Type="passive"->Temp, which seems neither
>         documented (I could have missed that) nor intuitive (for me).

Here 5 is in milli degrees. So it is too low, so this may be the cause.

>       * My current config defines "parallel" for both fans, further
>         all other attributes are identical, nevertheless the values
>         set (0...255) differ on both fans. E.g., CPUFan: 255 GFXFan:
>         215 ... Seems like I do not understand this option, could you
>         maybe explain why this happens?
>         
You can have multiple cooling devices to be active on certain
temperature. If Parallel then all these devices are started, otherwise
default is the previous cooling device need to reach max state before
the next device is activated.
> 
Certainly extending man pages with examples and clarifications are
welcome.

Thanks,
Srinivas

**Comment by daringer** [comment] 2015-07-19 15:14
Hey again, man-page updates incoming, guidance needed ;)

while hunting after a (unreal) "bug", which lead to a "max" trip-point temp of 4800m° recently, I found out (or finally understood why) that the "influence" parameter inside a cooling device scales the individual trip point using the relative influence of each cooling device inside the trip-point.

The latter is described inside the man pages, the former is for sure smart but imho a little counter-intuitive. For me the man-pages state the fact, that "influence" defines which cooling device is used "earlier", after knowing it, it seems clear---nevertheless, until now I would have guessed it's a given "time" after which the next cooling device is activated.

Collected the following points to be added/edited to the man-pages, would be great if you extend/edit it, especially the bigger ones would be nice to have them discussed before it turns out as waste of time---before I apply them I would rather hear your opinion about it:

- Despite the "active","passive" and "max" trip-point-types there are "critical" and "polling" the auto-discovery uses them, why not allowing the user to do so? "critical" leads directly to a reboot, this should also be in the man-pages.  (and btw. really reboot? why not standby? configurable command to be executed maybe? would you want a patch for the "arbitrary-command-on-critical-temp-thing?)...."Polling" is also not documented, but the source-code does not yet make this fully clear to me, could you explain the thoughts behind it?... So: documenting all available trip-point-types: "active", "passive", "max", "critical", "polling"
- The amount of examples inside "man thermal-conf.xml" seems good on the first view, but xml-configs have---for obvious reasons---a lousy information to space ratio, thus one is inclined to skip them or is doomed to scrolling (a lot for a man-page) and searching ... I would suggest to remove *all* example configurations from the man-page and replace them with 
  - a list of all config attributes with an short description (xpath-ing them maybe so the xml-hierarchy is transported as well), as e.g., "ReadBack" is simply omitted from the documentation, just two examples use it, but without further info, those are pretty useless. 
  - place some complete config files inside `/usr/share/thermald/` as often found in other daemons/config-heavy-applications 
  - adding a small "walk-through" for the creation of an own config file step by step using just single example lines and a final (example) config from `/usr/share/thermald`. 
- Finally, some semi-obvious facts are imho missing inside the man-pages. Once you know, there are obvious, but before, not right away:
  - clearly describe the relation between `<influence>` and the trip-point-temp, make the wording less ambiguous, e.g., clearly state "earlier" means a lower temp 
  - presenting an example with `<influence>100</influence>` has mislead me to the aforementioned `max temp = 8000m°`, as I've inserted an one digit influence inside the other cooling-device, personally I would fully omit `<influence>` in not-overly-specialized configs, clearly mark it optional, default 1:1 influence should work in most scenarios
  - there is a `--poll-interval` option, which defaults to 4(?)---some value. The config allows to set a "SamplingPeriod", the man-pages should define their relation... is it a simple `refresh = samplingperiod*pollintervall` or something slot based, or even unrelated?
  - what makes a sensor an async_sensor? The auto-discover feature finds at least one inside my laptop, but if the auto-discover can determine whether it is an async_sensor or not, the config could (like influence) widely ignore it as it is auto-detected, so the option would also be fully optional if one is not happy with the auto-discovery result.
  - "passive" / "active" is used in a misleading way. At the top to describe "active and passive cooling devices", but later those two are reused in a similar but distinct context. (an "active" trip-point -> performance, "passive" -> quiet). Personally I would fully discard (or at least shorten) the "A cooling  device  can  be  either active or passive" text/section, as it delivers only pretty obvious wikipedia-knowledge.

Collected "some" ideas ;) 
greetings

**Comment by spandruvada** [comment] 2015-07-20 17:14
On Sun, 2015-07-19 at 08:14 -0700, Markus Meissner wrote:
> Hey again, man-page updates incoming, guidance needed ;)
> 
> while hunting after a (unreal) "bug", which lead to a "max" trip-point
> temp of 4800m° recently, I found out (or finally understood why) that
> the "influence" parameter inside a cooling device scales the
> individual trip point using the relative influence of each cooling
> device inside the trip-point.
> 
> The latter is described inside the man pages, the former is for sure
> smart but imho a little counter-intuitive. For me the man-pages state
> the fact, that "influence" defines which cooling device is used
> "earlier", after knowing it, it seems clear---nevertheless, until now
> I would have guessed it's a given "time" after which the next cooling
> device is activated.
> 
> Collected the following points to be added/edited to the man-pages,
> would be great if you extend/edit it, especially the bigger ones would
> be nice to have them discussed before it turns out as waste of
> time---before I apply them I would rather hear your opinion about it:
> 
>       * Despite the "active","passive" and "max" trip-point-types
>         there are "critical" and "polling" the auto-discovery uses
>         them, why not allowing the user to do so?
User can configure "critical", not "polling". Polling has only internal
use for devices which support asynchronous temperature threshold
notification, but you need to start polling once a temperature threshold
is reached, so that we will not miss rapid temperature changes.

>       *  "critical" leads directly to a reboot, this should also be in
>         the man-pages. (and btw. really reboot? 
We can add it.

>       * why not standby?
Many Linux laptops can't enter standby.
>       * configurable command to be executed maybe? would you want a
>         patch for the
>         "arbitrary-command-on-critical-temp-thing?)...."Polling" is
>         also not documented, but the source-code does not yet make
>         this fully clear to me, could you explain the thoughts behind
>         it?... So: documenting all available trip-point-types:
>         "active", "passive", "max", "critical", "polling"
>       * The amount of examples inside "man thermal-conf.xml" seems
>         good on the first view, but xml-configs have---for obvious
>         reasons---a lousy information to space ratio, thus one is
>         inclined to skip them or is doomed to scrolling (a lot for a
>         man-page) and searching ... I would suggest to remove all
>         example configurations from the man-page and replace them with
Usually user tend to be more looking at man pages than examples in some
folders. So it is better to have examples by fixing the formatting, so
that they are more readable.
>       *  
>               * a list of all config attributes with an short
>                 description (xpath-ing them maybe so the xml-hierarchy
>                 is transported as well), as e.g., "ReadBack" is simply
>                 omitted from the documentation, just two examples use
>                 it, but without further info, those are pretty
>                 useless. 
>               * place some complete config files
>                 inside /usr/share/thermald/ as often found in other
>                 daemons/config-heavy-applications 
>               * adding a small "walk-through" for the creation of an
>                 own config file step by step using just single example
>                 lines and a final (example) config
>                 from /usr/share/thermald. 
>       * Finally, some semi-obvious facts are imho missing inside the
>         man-pages. Once you know, there are obvious, but before, not
>         right away: 
>               * clearly describe the relation between <influence> and
>                 the trip-point-temp, make the wording less ambiguous,
>                 e.g., clearly state "earlier" means a lower temp
Yes
>               *  
>               * presenting an example with <influence>100</influence>
>                 has mislead me to the aforementioned max temp = 8000m
>                 °, as I've inserted an one digit influence inside the
>                 other cooling-device, personally I would fully omit
>                 <influence> in not-overly-specialized configs, clearly
>                 mark it optional, default 1:1 influence should work in
>                 most scenarios
>               * there is a --poll-interval option, which defaults to
>                 4(?)---some value. The config allows to set a
>                 "SamplingPeriod", the man-pages should define their
>                 relation... is it a simple refresh =
>                 samplingperiod*pollintervall or something slot based,
>                 or even unrelated?
>               * what makes a sensor an async_sensor? The auto-discover
>                 feature finds at least one inside my laptop, but if
>                 the auto-discover can determine whether it is an
>                 async_sensor or not, the config could (like influence)
>                 widely ignore it as it is auto-detected, so the option
>                 would also be fully optional if one is not happy with
>                 the auto-discovery result.
>               * "passive" / "active" is used in a misleading way. At
>                 the top to describe "active and passive cooling
>                 devices", but later those two are reused in a similar
>                 but distinct context. (an "active" trip-point ->
>                 performance, "passive" -> quiet). Personally I would
>                 fully discard (or at least shorten) the "A cooling
>                 device can be either active or passive" text/section,
>                 as it delivers only pretty obvious
>                 wikipedia-knowledge.
passive means no fan so it is quiet mode. We can add comment that they
mean same.
> 
> Collected "some" ideas ;) 

Thanks for your ideas. If you have some changes, please submit them.

Thanks,
Srinivas

**Closed** 2017-06-30 17:51 UTC
