### ISSUE TITLE
sensor id 7 : No temp sysfs for readin

### ISSUE THREAD

**Issue by kroese** [intel/thermal_daemon#351] opened 2022-05-16 01:21 UTC
On a Intel Celeron N5105 I get the following errors:
```

sensor id 7 : No temp sysfs for readin

Manufacturer didn't provide adequate optimized configuration on Linux with You may want to disable thermald 

Unable to find a zone for SEN3
```

Is there anything we can do to workaround this? Because the `sensors` command can read the CPU temp correctly, so why doesnt thermald fallback to these values if it cannot read them?

**Comment by spandruvada** [comment] 2022-06-07 17:57
Do you have full log by running,
# systemctl stop thermald
#thermald --no-daemon --loglevel=info --adaptive

**Comment by timhae** [comment] 2022-08-28 08:19
same issue on Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
```
[1661674570][INFO]RAPL domain count 1
[1661674570][INFO]RAPL domain count 1
[1661674570][MSG]22 CPUID levels; family:model:stepping 0x6:8e:a (6:142:10)
[1661674570][MSG]22 CPUID levels; family:model:stepping 0x6:8e:a (6:142:10)
[1661674570][INFO]sensor_update: type SEN1
[1661674570][INFO]sensor_update: type GEN1
[1661674570][INFO]sensor_update: type B0D4
[1661674570][INFO]sensor_update: type pch_skylake
[1661674570][INFO]sensor_update: type SEN2
[1661674570][INFO]sensor_update: type INT3400
[1661674570][INFO]sensor_update: type x86_pkg_temp
[1661674570][INFO]sensor_update: type acpitz
[1661674570][INFO]sensor_update: type TMEM
[1661674570][INFO]thd_read_default_thermal_sensors loaded 9 sensors 
[1661674570][INFO]dts /sys/devices/platform/coretemp.0/name doesn't exist
[1661674570][MSG]sensor id 12 : No temp sysfs for reading raw temp
[1661674570][MSG]sensor id 12 : No temp sysfs for reading raw temp
[1661674570][MSG]sensor id 12 : No temp sysfs for reading raw temp
[1661674570][INFO]sensor index:2 SEN1 /sys/class/thermal/thermal_zone2/ Async:0 
[1661674570][INFO]sensor index:0 GEN1 /sys/class/thermal/thermal_zone0/ Async:0 
[1661674570][INFO]sensor index:7 B0D4 /sys/class/thermal/thermal_zone7/ Async:0 
[1661674570][INFO]sensor index:5 pch_skylake /sys/class/thermal/thermal_zone5/ Async:0 
[1661674570][INFO]sensor index:3 SEN2 /sys/class/thermal/thermal_zone3/ Async:0 
[1661674570][INFO]sensor index:1 INT3400 /sys/class/thermal/thermal_zone1/ Async:0 
[1661674570][INFO]sensor index:8 x86_pkg_temp /sys/class/thermal/thermal_zone8/ Async:1 
[1661674570][INFO]sensor index:6 acpitz /sys/class/thermal/thermal_zone6/ Async:0 
[1661674570][INFO]sensor index:4 TMEM /sys/class/thermal/thermal_zone4/ Async:0 
[1661674570][INFO]sensor index:9 hwmon /sys/class/hwmon/hwmon6/temp1_input Async:0 
[1661674570][INFO]sensor index:10 hwmon /sys/class/hwmon/hwmon6/temp2_input Async:0 
[1661674570][INFO]sensor index:11 hwmon /sys/class/hwmon/hwmon6/temp3_input Async:0 
[1661674570][INFO]thd_read_default_cooling devices loaded 11 cdevs 
[1661674570][INFO]ppcc limits max:17000000 min:7000000  min_win:25000000 step:1000000
[1661674570][INFO]set_pid_param 11 [-1000.100,10]
[1661674570][INFO]ppcc limits max:17000000 min:7000000  min_win:25000000 step:1000000
[1661674570][INFO]set_pid_param 12 [-1000.100,10]
[1661674570][INFO]Disable rapl-msr interface and use rapl-mmio
[1661674570][INFO]Use Default pstate drv settings
[1661674570][INFO]name = package-0
[1661674570][INFO]name = dram
[1661674570][INFO]sysfs read failed /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/intel-rapl:0:2/constraint_0_max_power_uw
[1661674570][INFO]:powercap RAPL invalid max power limit range 
[1661674570][INFO]Calculate dynamically phy_max 
[1661674570][INFO]1: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
[1661674570][INFO]8: intel_powerclamp, C:-1 MN: 0 MX:50 ST:5 pt:/sys/class/thermal/ rd_bk 0 
[1661674570][INFO]6: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
[1661674570][INFO]4: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
[1661674570][INFO]2: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
[1661674570][INFO]0: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
[1661674570][INFO]10: ath10k_thermal, C:0 MN: 0 MX:100 ST:1 pt:/sys/class/thermal/ rd_bk 1 
[1661674570][INFO]9: TCC, C:2 MN: 0 MX:63 ST:1 pt:/sys/class/thermal/ rd_bk 1 
[1661674570][INFO]7: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
[1661674570][INFO]5: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
[1661674570][INFO]3: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
[1661674570][INFO]11: rapl_controller, C:17000000 MN: 200000000 MX:7000000 Inc ST:-2000000 Dec ST:-1000000 pt:/sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/ rd_bk 1 
[1661674570][INFO]12: rapl_controller_mmio, C:17000000 MN: 17000000 MX:7000000 Inc ST:-2000000 Dec ST:-1000000 pt:/sys/devices/virtual/powercap/intel-rapl-mmio/intel-rapl-mmio:0/ rd_bk 1 
[1661674570][INFO]13: intel_pstate, C:0 MN: 0 MX:10 ST:1 pt:/sys/devices/system/cpu/intel_pstate/ rd_bk 1 
[1661674570][INFO]14: rapl_controller_dram, C:100000000 MN: 100000000 MX:0 ST:-500000 pt:/sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/intel-rapl:0:2/ rd_bk 1 
[1661674570][INFO]15: LCD, C:0 MN: 0 MX:7500 ST:750 pt:/sys/class/backlight/intel_backlight/ rd_bk 1 
[1661674570][INFO]thd_read_default_thermal_zones loaded 9 zones 
[1661674570][INFO]INT3400 Base path is /sys/bus/acpi/devices/INT3400:00/physical_node/uuids/
[1661674570][INFO]Processor thermal device is present 
[1661674570][INFO]It will act as CPU thermal zone !! 
[1661674570][INFO]Processor thermal device passive Trip is 100050
[1661674570][INFO]

 ZONE DUMP BEGIN
[1661674570][INFO]
[1661674570][INFO]Zone 7: B0D4, Active:1 Bind:1 Sensor_cnt:1
[1661674570][INFO]..sensors.. 
[1661674570][INFO]sensor index:7 B0D4 /sys/class/thermal/thermal_zone7/ Async:0 
[1661674570][INFO]..trips.. 
[1661674570][INFO]index 3: type:active temp:95050 hyst:1000 zone id:7 sensor id:7 control_type:1 cdev size:0
[1661674570][INFO]index 1: type:passive temp:100050 hyst:1000 zone id:7 sensor id:7 control_type:1 cdev size:4
[1661674570][INFO]cdev[0] rapl_controller, Sampling period: 0
[1661674570][INFO]	 target_state:not defined
[1661674570][INFO]cdev[1] intel_pstate, Sampling period: 0
[1661674570][INFO]	 target_state:not defined
[1661674570][INFO]cdev[2] intel_powerclamp, Sampling period: 0
[1661674570][INFO]	 target_state:not defined
[1661674570][INFO]cdev[3] Processor, Sampling period: 0
[1661674570][INFO]	 target_state:not defined
[1661674570][INFO]index 2: type:active temp:100050 hyst:1000 zone id:7 sensor id:7 control_type:1 cdev size:0
[1661674570][INFO]index 0: type:critical temp:125050 hyst:1000 zone id:7 sensor id:7 control_type:1 cdev size:0
[1661674570][INFO]index 4: type:polling temp:85545 hyst:0 zone id:7 sensor id:7 control_type:0 cdev size:0
[1661674570][INFO]
[1661674570][INFO]

 ZONE DUMP END
[1661674570][INFO]..ppcc dump begin.. 
[1661674570][INFO]ppcc dump end
[1661674570][INFO]..psvt dump begin.. 
[1661674570][INFO]Name :IETM.D0
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.B0D4 priority:10 sample_period:10 temp:100 domain:9 control_knob:65536 psv.limit:max
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.TMEM priority:10 sample_period:30 temp:95 domain:9 control_knob:65536 psv.limit:max
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.SEN1 priority:10 sample_period:50 temp:63 domain:9 control_knob:65536 psv.limit:15000
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.GEN1 priority:10 sample_period:30 temp:80 domain:9 control_knob:65536 psv.limit:max
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.SEN2 priority:10 sample_period:160 temp:68 domain:9 control_knob:65536 psv.limit:21000
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.SEN2 priority:9 sample_period:160 temp:74 domain:9 control_knob:65536 psv.limit:15000
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.SEN2 priority:8 sample_period:160 temp:80 domain:9 control_knob:65536 psv.limit:15000
[1661674570][INFO]Name :close
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.B0D4 priority:10 sample_period:10 temp:100 domain:9 control_knob:65536 psv.limit:max
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.TMEM priority:10 sample_period:30 temp:95 domain:9 control_knob:65536 psv.limit:max
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.SEN1 priority:10 sample_period:50 temp:63 domain:9 control_knob:65536 psv.limit:15000
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.GEN1 priority:10 sample_period:30 temp:80 domain:9 control_knob:65536 psv.limit:max
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.SEN2 priority:10 sample_period:160 temp:68 domain:9 control_knob:65536 psv.limit:21000
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.SEN2 priority:9 sample_period:160 temp:74 domain:9 control_knob:65536 psv.limit:15000
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.SEN2 priority:8 sample_period:160 temp:80 domain:9 control_knob:65536 psv.limit:15000
[1661674570][INFO]Name :open
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.B0D4 priority:10 sample_period:10 temp:100 domain:9 control_knob:65536 psv.limit:max
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.TMEM priority:10 sample_period:30 temp:95 domain:9 control_knob:65536 psv.limit:max
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.SEN1 priority:10 sample_period:50 temp:58 domain:9 control_knob:65536 psv.limit:min
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.GEN1 priority:10 sample_period:30 temp:80 domain:9 control_knob:65536 psv.limit:max
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.SEN2 priority:10 sample_period:160 temp:68 domain:9 control_knob:65536 psv.limit:21000
[1661674570][INFO]	 source:\_SB_.PCI0.B0D4 target:\_SB_.PCI0.LPCB.ECDV.SEN2 priority:9 sample_period:160 temp:74 domain:9 control_knob:65536 psv.limit:15000
[1661674570][INFO]psvt dump end
[1661674570][INFO]..apat dump begin.. 
[1661674570][INFO]target_id:1 name:close participant:\_SB_.IETM domain:14 code:PSVT argument:close
[1661674570][INFO]target_id:2 name:open participant:\_SB_.IETM domain:14 code:PSVT argument:open
[1661674570][INFO]apat dump end
[1661674570][INFO]..apct dump begin.. 
[1661674570][INFO]condition_set 0
[1661674570][INFO]	target:1 device: condition:Lid_state comparison:ADAPTIVE_EQUAL argument:0 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:1 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:1 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:1 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:1 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:1 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:1 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:1 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:1 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:1 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:INVALID time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]condition_set 1
[1661674570][INFO]	target:2 device: condition:Lid_state comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:2 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:2 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:2 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:2 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:2 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:2 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:2 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:2 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:AND time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]	target:2 device: condition:Default comparison:ADAPTIVE_EQUAL argument:1 operation:INVALID time_comparison:0 time:0 stare:0 state_entry_time:0 
[1661674570][INFO]..apct dump end.. 
[1661674570][INFO]Power slider is now set to 75
[1661674570][INFO]Condition Set matched:1 target:2
[1661674570][INFO]adaptive engine reached end
[1661674570][INFO]Running on a vanilla kernel
[1661674570][MSG]Polling mode is enabled: 4
[1661674570][INFO]Current user preference is 0
[1661674570][INFO]Control is taken over from kernel
[1661674570][INFO]INT3400 Base path is /sys/bus/acpi/devices/INT3400:00/physical_node/uuids/
[1661674570][INFO]Taking over thermal control 
[1661674570][INFO]thd_engine_thread begin
[1661674570][INFO]Set Default UUID: 63BE270F-1C11-48FD-A6F7-3AF253FF3E2D
[1661674570][INFO]Thermal zone of type SEN1
[1661674570][INFO]Thermal zone of type GEN1
[1661674570][INFO]Thermal zone of type B0D4
[1661674570][INFO]Thermal zone of type pch_skylake
[1661674570][INFO]Thermal zone of type SEN2
[1661674570][INFO]Thermal zone of type INT3400
[1661674570][INFO]Thermal zone of type x86_pkg_temp
[1661674570][INFO]Thermal zone of type acpitz
[1661674570][INFO]Thermal zone of type TMEM
[1661674574][INFO]op->device:rapl_controller 18000000
[1661674574][INFO]set cdev state index 11 state 18000000 wr:18000000
[1661674574][INFO]Set : threshold:100050, temperature:41050, cdev:11(rapl_controller), curr_state:18000000, max_state:7000000
[1661674574][WARN]Manufacturer didn't provide adequate support to run in
[1661674574][WARN]optimized configuration on Linux with open source
[1661674574][WARN]You may want to disable thermald on this system if you see issue
[1661674574][INFO]IETM_D0 processed
[1661674574][INFO]forced to min_state 
[1661674574][INFO]set cdev state index 11 state 200000000 wr:200000000
[1661674574][INFO]Set : 0, 0, 11, 200000000, 7000000
[1661674574][INFO]Name :IETM.D0
[1661674574][INFO]

 ZONE DUMP BEGIN
[1661674574][INFO]
[1661674574][INFO]Zone 2: SEN1, Active:1 Bind:1 Sensor_cnt:1
[1661674574][INFO]..sensors.. 
[1661674574][INFO]sensor index:2 SEN1 /sys/class/thermal/thermal_zone2/ Async:1 
[1661674574][INFO]..trips.. 
[1661674574][INFO]index 0: type:passive temp:63000 hyst:0 zone id:2 sensor id:2 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 5
[1661674574][INFO]	 target_state:15000000
[1661674574][INFO]index 1: type:polling temp:56700 hyst:0 zone id:2 sensor id:2 control_type:0 cdev size:0
[1661674574][INFO]
[1661674574][INFO]
[1661674574][INFO]Zone 0: GEN1, Active:1 Bind:1 Sensor_cnt:1
[1661674574][INFO]..sensors.. 
[1661674574][INFO]sensor index:0 GEN1 /sys/class/thermal/thermal_zone0/ Async:1 
[1661674574][INFO]..trips.. 
[1661674574][INFO]index 0: type:passive temp:81000 hyst:0 zone id:0 sensor id:0 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 3
[1661674574][INFO]	 target_state:not defined
[1661674574][INFO]index 1: type:polling temp:72000 hyst:0 zone id:0 sensor id:0 control_type:0 cdev size:0
[1661674574][INFO]
[1661674574][INFO]
[1661674574][INFO]Zone 7: B0D4, Active:1 Bind:1 Sensor_cnt:1
[1661674574][INFO]..sensors.. 
[1661674574][INFO]sensor index:7 B0D4 /sys/class/thermal/thermal_zone7/ Async:0 
[1661674574][INFO]..trips.. 
[1661674574][INFO]index 0: type:passive temp:101000 hyst:0 zone id:7 sensor id:7 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 1
[1661674574][INFO]	 target_state:not defined
[1661674574][INFO]index 1: type:polling temp:90000 hyst:0 zone id:7 sensor id:7 control_type:0 cdev size:0
[1661674574][INFO]
[1661674574][INFO]
[1661674574][INFO]Zone 3: SEN2, Active:1 Bind:1 Sensor_cnt:1
[1661674574][INFO]..sensors.. 
[1661674574][INFO]sensor index:3 SEN2 /sys/class/thermal/thermal_zone3/ Async:1 
[1661674574][INFO]..trips.. 
[1661674574][INFO]index 0: type:passive temp:68000 hyst:0 zone id:3 sensor id:3 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 16
[1661674574][INFO]	 target_state:21000000
[1661674574][INFO]index 2: type:passive temp:74000 hyst:0 zone id:3 sensor id:3 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 16
[1661674574][INFO]	 target_state:15000000
[1661674574][INFO]index 3: type:passive temp:80000 hyst:0 zone id:3 sensor id:3 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 16
[1661674574][INFO]	 target_state:15000000
[1661674574][INFO]index 3: type:polling temp:61200 hyst:0 zone id:3 sensor id:3 control_type:0 cdev size:0
[1661674574][INFO]
[1661674574][INFO]
[1661674574][INFO]Zone 4: TMEM, Active:1 Bind:1 Sensor_cnt:1
[1661674574][INFO]..sensors.. 
[1661674574][INFO]sensor index:4 TMEM /sys/class/thermal/thermal_zone4/ Async:1 
[1661674574][INFO]..trips.. 
[1661674574][INFO]index 0: type:passive temp:96000 hyst:0 zone id:4 sensor id:4 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 3
[1661674574][INFO]	 target_state:not defined
[1661674574][INFO]index 1: type:polling temp:85500 hyst:0 zone id:4 sensor id:4 control_type:0 cdev size:0
[1661674574][INFO]
[1661674574][INFO]

 ZONE DUMP END
[1661674574][INFO]Condition Set matched:1 target:2
[1661674574][INFO]Target Name:open
[1661674574][INFO]looking for cdev IETM
[1661674574][INFO]cdev IETM not found
[1661674574][INFO]set_int3400 target open
[1661674574][INFO]

 ZONE DUMP BEGIN
[1661674574][INFO]
[1661674574][INFO]Zone 2: SEN1, Active:1 Bind:1 Sensor_cnt:1
[1661674574][INFO]..sensors.. 
[1661674574][INFO]sensor index:2 SEN1 /sys/class/thermal/thermal_zone2/ Async:1 
[1661674574][INFO]..trips.. 
[1661674574][INFO]index 0: type:passive temp:58000 hyst:0 zone id:2 sensor id:2 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 5
[1661674574][INFO]	 target_state:not defined
[1661674574][INFO]index 1: type:polling temp:52200 hyst:0 zone id:2 sensor id:2 control_type:0 cdev size:0
[1661674574][INFO]
[1661674574][INFO]
[1661674574][INFO]Zone 0: GEN1, Active:1 Bind:1 Sensor_cnt:1
[1661674574][INFO]..sensors.. 
[1661674574][INFO]sensor index:0 GEN1 /sys/class/thermal/thermal_zone0/ Async:1 
[1661674574][INFO]..trips.. 
[1661674574][INFO]index 0: type:passive temp:81000 hyst:0 zone id:0 sensor id:0 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 3
[1661674574][INFO]	 target_state:not defined
[1661674574][INFO]index 1: type:polling temp:72000 hyst:0 zone id:0 sensor id:0 control_type:0 cdev size:0
[1661674574][INFO]
[1661674574][INFO]
[1661674574][INFO]Zone 7: B0D4, Active:1 Bind:1 Sensor_cnt:1
[1661674574][INFO]..sensors.. 
[1661674574][INFO]sensor index:7 B0D4 /sys/class/thermal/thermal_zone7/ Async:0 
[1661674574][INFO]..trips.. 
[1661674574][INFO]index 0: type:passive temp:101000 hyst:0 zone id:7 sensor id:7 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 1
[1661674574][INFO]	 target_state:not defined
[1661674574][INFO]index 1: type:polling temp:90000 hyst:0 zone id:7 sensor id:7 control_type:0 cdev size:0
[1661674574][INFO]
[1661674574][INFO]
[1661674574][INFO]Zone 3: SEN2, Active:1 Bind:1 Sensor_cnt:1
[1661674574][INFO]..sensors.. 
[1661674574][INFO]sensor index:3 SEN2 /sys/class/thermal/thermal_zone3/ Async:1 
[1661674574][INFO]..trips.. 
[1661674574][INFO]index 0: type:passive temp:68000 hyst:0 zone id:3 sensor id:3 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 16
[1661674574][INFO]	 target_state:21000000
[1661674574][INFO]index 2: type:passive temp:74000 hyst:0 zone id:3 sensor id:3 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 16
[1661674574][INFO]	 target_state:15000000
[1661674574][INFO]index 2: type:polling temp:61200 hyst:0 zone id:3 sensor id:3 control_type:0 cdev size:0
[1661674574][INFO]
[1661674574][INFO]
[1661674574][INFO]Zone 4: TMEM, Active:1 Bind:1 Sensor_cnt:1
[1661674574][INFO]..sensors.. 
[1661674574][INFO]sensor index:4 TMEM /sys/class/thermal/thermal_zone4/ Async:1 
[1661674574][INFO]..trips.. 
[1661674574][INFO]index 0: type:passive temp:96000 hyst:0 zone id:4 sensor id:4 control_type:1 cdev size:1
[1661674574][INFO]cdev[0] rapl_controller_mmio, Sampling period: 3
[1661674574][INFO]	 target_state:not defined
[1661674574][INFO]index 1: type:polling temp:85500 hyst:0 zone id:4 sensor id:4 control_type:0 cdev size:0
[1661674574][INFO]
[1661674574][INFO]

 ZONE DUMP END
[1661674575][MSG]Terminating ...
[1661674576][MSG]terminating on user request ..
[1661674576][INFO]Giving up thermal control
```

**Comment by timhae** [comment] 2022-08-28 08:24
probably fine and duplicate of #323 and #205 sorry for the noise

**Closed** 2024-07-17 06:34 UTC
